# Generated by Django 5.1.6 on 2025-03-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_is_admin_user_is_staff_user_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
